### ISSUE TITLE
CGFX stopped working

### ISSUE THREAD

**Issue by DocDrazen** [shonumi/gbe-plus#113]
Hello! Wasn't really sure where to ask about this so figured this would be the best place to try and get some help.

Been working on adding color to Castlevania Legends. I finished the entirety of level 1 except for the boss and the Axe collectible.

Edited color for the Axe, which not really sure if it's relevant or not. But afterwards the game won't load any of the sprites I've made for it. The manifest list still shows all of my stuff there with the sprites colored in. But it just won't load any more. Not really sure if there's a way to check what would've caused that or how I can restore everything I did. Load custom gfx is checked and I'm still launching the game by dragging and dropping the rom file into the emulator. 

Any advice would be appreciated!

**Comment by DocDrazen** [comment]
I fixed it manifest had around 700 entries so far. Not sure how it happened but one line started with a / instead of a bracket and there also looked like a dump of an object but the name of it was really bizarre. Deleted both lines and I'm working.

**Comment by shonumi** [comment]
FWIW, Custom Graphics are essentially unmaintained at this point. I haven't touched this feature in years, and I have no serious interest in picking it up again. The current implementation has a lot of technical shortcomings (mostly GBC specific, but some DMG too). There are workable solutions to those, but it's not something I think I'll actively pursue any time in the near future. There's also the issue of the UI and general process of dumping, editing, and testing graphics. The Qt code is a nightmare, and the user experience is rather challenging without proper, detailed guidance.

Nothing in GBE+'s DMG/GBC core should break Custom Graphics, so I don't see this feature suddenly not working on day after some random change to the master branch. But going forward, I'm not planning on working on Custom Graphics or resolving some of its long-standing issues. It's still hanging around the codebase as a legacy, in effect. It's a cool idea but disproportionately cumbersome to implement even halfway decent, which is why my efforts are elsewhere these days.

I'm glad you got your manifest fixed though! Just wanted to let you know the current status of custom graphics in GBE+.

**Comment by DocDrazen** [comment]
That's totally understandable. I'm glad it's still in the emulator at least. It's a whole endeavor dumping everything, redoing them in Gimp, and then getting them back in but it's been worth it for me. I've been trying to find ways of colorizing a Gameboy game but so far this is the best way I've seen. 

https://youtu.be/o-xePqU-vX8

This is what I've gotten so far. I think it's turned out pretty well so far. I think you definitely did some good work on the cgfx though regardless. :D
