### ISSUE TITLE
Loading ANY game crashes the emulator.

### ISSUE THREAD

**Issue by NoveltyMan** [shonumi/gbe-plus#128]
Loading ANY game crashes the emulator, no matter if it's .gb, .gbc, or .gba, and not all files even show up despite being a GAMEBOY ROM THAT ACTUALLY RUNS FINE ON EVERY OTHER EMULATOR.
When loading a rom, only a empty white screen appears and makes some fart-like sounds and then everything stops working.
This emulator is a useless piece of trash and a waste of disk space.

**Comment by shonumi** [comment]
> This emulator is a useless piece of trash and a waste of disk space.

Okay... That's a weird way to ask for help, starting off with an insult...

Anyway, you need to provide more information about your situation if you want an issue like this looked into. Some useful details would be:

1) Operating system used where the issue occurs.

2) Version or revision of GBE+ (and probably whether you compiled it yourself or not).

3) UI of GBE+ used (SDL or Qt5) and the method of opening the file (e.g. via command line arguments, drag and drop, or Qt file selector).

After that, we can see what's causing the problem by narrowing down other possibilities. FWIW, GBE+ is tested both on Linux and Windows 10 before each release. There were no observable crashes in my testing session on April 1st on either OS when opening and running files. However, a known crash does exist in the Qt5 version on Windows (but not Linux) when closing the program, as stated in the release notes.

So if I had to guess, it's something else not playing right with GBE+ that's the source of your current problems. Hopefully it's easy enough to resolve once your situation becomes a bit clearer.

**Comment by NoveltyMan** [comment]
Latest Windows.
1.2
File selector in the qt.

**Comment by shonumi** [comment]
I assume you mean you're using 1.6 instead of 1.2, correct?

I'm going to guess you haven't set up GBE+'s folder in AppData yet? GBE+ requires its own folder there to properly access some of its files and folders. Make a folder like such:

    C:\Users\[YOUR USERNAME]\AppData\Local\gbe_plus

Replace [YOUR USERNAME] with the appropriate username for your system. Copy the **data** folder that comes with GBE+ along with the **gbe.ini** file. Note that the most recent download inadvertently omitted the .ini file, so you can download it directly from GitHub [here](https://raw.githubusercontent.com/shonumi/gbe-plus/master/src/gbe.ini).

Once you have both the **data** folder and **GBE.ini** file in `AppData\Local\gbe_plus`, launch the QT version again and see if the errors persist. If the do, take note of the command line console that pops up and copy any text that shows up.

**Comment by NoveltyMan** [comment]
![image](https://user-images.githubusercontent.com/50550439/163863236-8be552ce-b21a-4319-b6f1-ab96ec87291a.png)
![image](https://user-images.githubusercontent.com/50550439/163863293-29e2591f-8b87-4a8d-a776-b6aa46155413.png)
No difference at all. Nothing works.

**Comment by shonumi** [comment]
Looks like you really are using GBE+ 1.2. That version was released **years** ago and is no longer supported. Use 1.6 or something newer if you want further assistance here.

It's probably worth noting that in the first screenshot you're trying to load a .ZIP file (unsupported in any version of GBE+) and in both cases it looks like you're trying to load a ROM from a folder that has non-ASCII characters, which would also cause potential problems with Qt.

**Comment by shonumi** [comment]
Closed as an invalid issue.
