### ISSUE TITLE
Windows 1.0 Beta dependencies issue

### ISSUE THREAD

**Issue by SonofUgly** [shonumi/gbe-plus#23]
Running on Win8.1 x64, get system errors saying program can't run without:
```
libwinpthread-1.dll
libstdc++-6.dll
libgcc_s_dw2-1.dll
```
After adding those (x86, built using mingw-w64 4.9.2), it crashes with:
```
The procedure entry point
_ZNKSt7_cxx1112basic_stringlcSt11char_traitlcESalcEE12find_last_ofEP
Kcjj could not be located in the dynamic link library
F:\...\gbe_plus_qt.exe
```

**Comment by shonumi** [comment]
Thanks for the report!

Those entry point errors are due to the dlls not being exactly the same version the exe expects. I believe the issue is that my compiler (MinGW g++) did not link to things statically. I've gotten similar issues with the old GBE project. It should be a simple fix in CMake. Let me get back to you later tonight.

**Comment by shonumi** [comment]
@SonofUgly - Can you try the new RC 1? Here's the link: https://goo.gl/UqAqa8

I tried it on a clean version of Windows 7 and it worked. Hopefully all the .dlls are included that are necessary this time ;)

**Comment by SonofUgly** [comment]
Yep, it's all working now. Thanks.

**Comment by shonumi** [comment]
Great to hear that. I spent all night trying to get this stuff working. I didn't think MinGW and Qt would be this much of a hassle. At least building on Windows is sorted, more or less.

**Comment by MarcoEstevez** [comment]
Great Job, thanks
