### ISSUE TITLE
Dynamic Rate Control(DRC)

### ISSUE THREAD

**Issue by ADormant** [shonumi/gbe-plus#28]
This would help reduce stuttering.
https://github.com/libretro/RetroArch/wiki/Getting-optimal-vsync-performance
https://github.com/libretro/RetroArch/tree/master/audio

**Comment by shonumi** [comment]
What specific use cases would this feature solve? That is tosay, what scenarios have you encountered that had stuttering audio? GB and GBA sound has support for reasonable audio stretching (as long as game speed does not approach 0% or something like that). So slowdowns won't make stuttering audio, not like Dolphin used to have. GBA sound is scratchy at many times, but this is a separate issue and not actual stuttering.

So, I'm trying to understand what this feature would actually improve, since GBE+ should handle stuttering as-is.

**Comment by ADormant** [comment]
It's not that I encountered stuttering in GBE+ in particular I expressed it wrong but it woud help make gameplay smoother and more similar to the actual console. It is supposed to synchronize audio and stereo better.
@shonumi

**Comment by shonumi** [comment]
Okay, I see. However, VSync stuff ideally should be left up to the OpenGL drivers (when using OpenGL). When I upgrade to SDL 2.0, SDL will handle VSync on the software blitting. It's too early to focus on other solutions at this point though.

**Comment by ADormant** [comment]
@shonumi I think DRC can and should run concurrently with V-Sync or even G-Sync or FreeSync.

**Comment by shonumi** [comment]
Closing this since I'm still not certain what DRC could really add to GBE+, or if it even solves a current problem.
