### ISSUE TITLE
Gameboy bugs

### ISSUE THREAD

**Issue by benderscruffy** [shonumi/gbe-plus#29]
Prehistorik Man (USA, Europe)
freezes up after the Titus screen

Altered Space - A 3-D Alien Adventure (USA)
 it freezes up straight away

Mortal Kombat & Mortal Kombat II (USA, Europe)
if you choose one or two it just resets back to the developers screen

Super Chinese Land 1.2.3. Dash (J)
which ever game you choose it resets back to the title screen

Pokemon Red-Blue 2-in-1 (U)
doesn't load either game

Initial D Gaiden (J)
blank white screen

**Comment by shonumi** [comment]
@benderscruffy - Thanks for the reports! I'll start looking into them case-by-case. Would you mind if you verified that these games work on other emulators if you have the chance? Also, feel free to simply add more games as additional comments (rather than editing) for better visibility (i.e. email alerts).

**Comment by benderscruffy** [comment]
ok no problem

**Comment by benderscruffy** [comment]
Boxing (Japan)
stuck on the first screen
cannot choose one or two players

**Comment by shonumi** [comment]
About Boxing, sounds like one of the few, rare games that actually use the Joypad IRQ. It wasn't recommended to use in a lot of game because it's not as reliable as other methods (manual polling on VBlank). Hopefully this one will be easy to fix.

Looking into Mortal Kombat. I had someone else check it out. Seems like BGB and real hardware (original cart and flashcarts) have that same issue. I'm not sure what kind of issue it is (since they actually sold some carts with this very defect in it, presumably) it's probably not an emulation issue specific to GBE+. I'm asking some more folks for info, because this is a real mystery.

**Comment by benderscruffy** [comment]
Ant Soldiers (Sachen) [!]
missing the icons from the bottom of the screen during gameplay
![32144253750559](https://cloud.githubusercontent.com/assets/2696404/14594884/36f77cfa-056d-11e6-988c-499b641236ab.png)

A-Force (Sachen 4-in-1 Vol. 6) (Unl) [!]
blank white screen

Bomberman Collection (J)
After you selected a game, it restarts back to the menu

Captain Knick-Knack (Sachen) [!] 
blank white screen

**Comment by benderscruffy** [comment]
Alleyway (World)
cannot move your paddle left or right

**Comment by shonumi** [comment]
Progress on Boxing. Seems it's not the JOYPAD IRQ, but the serial IRQ (which likewise has never been implemented). I got it to work, but the solution isn't perfect just yet. Probably the source of other freezes on menus for other games.

**Comment by sczther** [comment]
The multi-games looping back to menu are of two categories. Most of those should be a slightly modified MBC1, which should be a easy fix. Montomarou Collection 2 and possibly others use MMM01 mapper, which i guess was a later try at differentiating the multi-games more.
Some Sachen games don't even work on hardware, at least by standard methods. Possibly they use their own pirate obscure mappers and anti-piracy games (quite a lot of pirate games have those, oh the irony).
The Pinball Fantasies/Dreams/etc. games are a long known problem. The games work good on INaccurate emulators, and fail hard on the accurate ones. They probably require some very precise timing stuff or so.
Prehistorik Man is horribly complex, it's demoscene level of mindfuckery.
Gekkio's overview of special cart mappers: http://gekkio.fi/blog/2016-03-19-game-boy-cartridge-pcb-photos.html
Taisel's comments on GB emulation hurdles: https://www.reddit.com/r/emulation/comments/45oiip/mgba_now_has_support_for_gameboy_games/d00ckfw

Also, for the love of god, pleas don't use KiGB. I try to explain why here: http://emulation.gametechwiki.com/index.php/Game_Boy/Game_Boy_Color_emulators

**Comment by shonumi** [comment]
@sczther - Thanks for the info! I talked to gekkio and byuu and found out about MK 1&2 and the MBC1 variants. Hitting a bit of a brick wall with Boxing, so I think I'll switch focus to that. MAME has code to handle the MBC1 variants, but I wish people would **properly** document this stuff (i.e. write out what the differences are, in plain-old-English). I'm still scratching my head at their code, but the MBC1 variants don't seem incredibly complex.

Not worried about Sachen games at the moment (or ever? We'll see...) The thing about Prehistorik Man is that it was at least playable before in the old GBE project (when I was on Google Code). The intro does palette changes mid-scanline, which isn't too bad if you do a per-pixel renderer and try to do accurate cycle counting. But that would require a new DMG core altogether, because the current one was never intended to do that sort of stuff (most of the DMG code are remnants of my earliest emulation attempts). With a more accurate core though, Prehistorik Man's intro is straightforward to get right.

I'm actually very tempted to split my cores into "accurate" and "don't care, go fast" versions. This is probably necessary as the GBA is unbearably slow thanks to its per-pixel rendering and the way it tries to run hardware and controllers cycle-by-cycle. Per-pixel rendering isn't even needed for most GBA games, but it's simpler to write a renderer that way, imo.

I've never used KiGB though, to be honest :P

**Comment by sczther** [comment]
Documentation is scarce, praise anybody who does document their findings well :) I know MESS does it, and it's probably the only one, except from some hack KiGB throws at it.
So you want to rewrite the GB core completely? 
Pirate games are a chapter for themselves. There are unlicensed companies like Rocket, Wisdom Tree and Sachen, which have their own "mapper" and then there is a cluster of various odd things that asian pirate groups did. If you want to know more, read up on http://hhug.me/
I would be for that split if you know that you can handle having so many cores. Maybe only split the intensive parts like the rendering and leave the core functions? (I don't know enough about emulation and GB hardware to know how suitable that would be)

Good for you :P I was so amazed when I saw it's site, listing all the exclusive accuracy milestones. Then really surprised when I learned how bad and hacky it is. Gambatte/BGB have probably the best cores (for now), but a lot of various obscure emulators do many little things better (peripherals, etc.).

**Comment by benderscruffy** [comment]
i dont really care if it is full of hacks
it does the job (it plays games)
it was last updated in 2008
and there are other obsolete emulators other people use
of course there are more accurate emulators that is why i use BGB aswell

**Comment by sczther** [comment]
Yeah, Use what you want, no offense. I just want to debunk the myth of KiGB being very accurate and also remark that testing against inaccurate emulators can mislead you. For example KiGB corrects a few "graphical bugs" which happen on real hardware.

**Comment by shonumi** [comment]
As of 5a6f755d0aa2a3f9f86d71fc9542555a75b9064c, the following games are confirmed working:

Bomberman Collection (needed MBC1M multicart support)
Boxing (needed basic SIO emulation)
Initial D Gaiden (needed basic SIO emulation. BUT still has graphical issues in gameplay, so not perfect)
Momotarou Collection (Collection 2 is fine, but Collection 1 was broken, needed MBC1M multicart support)
Mortal Kombat 1 (needed basic SIO emulation)
Mortal Kombat 1 & 2 (needed MBC1M multicart support)

I have not taken a look at the rest except for Altered Space (which is still broken), but not bad for a week's worth of work.

**Comment by benderscruffy** [comment]
good job on the latest release
but there is still alot of the games on the list that still don't work
but hey no rush :)

**Comment by benderscruffy01** [comment]
Chiki Chiki Machine Mou Race (Japan)
missing hud from bottom of screen
![chiki](https://user-images.githubusercontent.com/48821663/55692285-149b2d00-59d9-11e9-9f75-a89e5fb37835.PNG)
endrift fixed
https://github.com/mgba-emu/mgba/commit/57ad372c782ef6ccd8cb776dca35d20a7076d006

**Comment by benderscruffy01** [comment]
Prehistorik Man (USA, Europe) scroller corrupt and white screen
on the title screen the scroller is corrupt
 when you go to start the gameplay nothing but a white screen
![prehistoric](https://user-images.githubusercontent.com/48821663/55701744-f2b89f00-5a06-11e9-9d62-21ce97d63984.PNG)

**Comment by benderscruffy01** [comment]
Altered Space - A 3-D Alien Adventure (USA)
it freezes up straight away

**Comment by benderscruffy01** [comment]
Hook (USA)
freezes up on the menu

**Comment by benderscruffy01** [comment]
Mr. Do! (USA)
freezes up on the very first screen

**Comment by shonumi** [comment]
Mr. Do! fixed **again** as of e5c7fd059ee8dd2e5bda0a60cf369ef0dd80bc56

Like the 3rd time I've "fixed" it... The game breaks at the drop of a hat.
