### ISSUE TITLE
Gameboy Color bugs 

### ISSUE THREAD

**Issue by benderscruffy** [shonumi/gbe-plus#30]
Minesweeper for 'Windows' (PD) [C]
as soon as you choose new game it freezes up

16 Threads Demo by DarkFader (PD) [C] 
blank white screen

Beat Mania GB 2 (J) [C]
blank white screen

Binary Chaos (PD) [C]
lots of graphic glitches

Color Panel Demo (PD) [C] 
The pattern display is not correct. 

Cool Hand (E) (M3) [C]
freezes up on the title screen

Demotronic Final Demo (PD) [C] 
The demo detected it was an emulator and refused to run. 

It Came from Planet Zilog (PD) (C)
few screens have graphic glitches then freezes up the emulator

Mary-Kate & Ashley - Crush Course (U) [C]
graphics are all corrupt

Ready 2 Rumble Boxing (U) [C]
speech is not correct and during gameplay there is graphic glitches

Warriors of Might and Magic (U) [C]
stuck on the title screen

Oddworld Adventures 2 (E) (M5) [C]
Missing speech at the title screen and at the Gamespeak option

Mental Respirator (PD) [C] 
3 of the demos dont work properly

**Comment by benderscruffy** [comment]
Cannon Fodder (USA) (En,Fr,De,Es,It)
music and sound fx dont play properly

**Comment by CaptainCaffeine** [comment]
I spent quite a bit of time debugging Warriors of Might and Magic this weekend, and managed to get it working in my emulator.

On the title screen (where GBE+ hangs) and on the picture of a castle after you start a new game (where my emulator was hanging), the game does the following busy loop waiting for scanline 0x90:

```
LDH A, (0xFF44)   ; PC=0x202B
CP 0x90           ; PC=0x202D
JR C, -0x06       ; PC=0x202F
```

When 0x90 is loaded into register A and the jump is not taken, the game begins to check for input, at which point pressing the A button brings you to the savefile screen. However, they left the VBLANK interrupt enabled during this time (which I'm almost positive was an error that they did not notice) causing the following to happen:

```
; A=0x8F
JR C, -0x06
; LY=0x8F
; LY=0x8F
; LY=0x8F

; A=0x8F
LDH A, (0xFF44)
; LY=0x8F
; LY=0x8F
; LY=0x8F    ; When the read occurs

; A=0x8F
CP 0x90
; LY=0x90    ; LY changes to 0x90 on the cycle after the read occurs, so A still contains 0x8F
; LY=0x90

VBLANK Interrupt
```

The VBLANK routine does a bunch of stuff, setting the background palette and some delay stuff if I remember correctly. That doesn't really matter though; what does matter is that it takes an incredibly long time to do so: just short of 152 scanlines. When it finally executes RETI and gets back to the busy loop, LY has looped back to 0x8E. The interrupt triggered before 0x90 could be read into register A, and so 0x8F is popped back into A, the comparison is failed, and 0x8E is then read into A again at the start of the loop. This repeats forever in GBE+, but my emulator did the following:

[LY=0x90 timing](https://gist.github.com/CaptainCaffeine/4b0b91c8dc63d7a0524b4e654b66f48a)

The interrupt routine takes 4 cycles less than an exact multiple of the number of cycles in a scanline, so each time my emulator inched closer to LY changing to 0x90 late enough for `LDH A, (0xFF44)` to get a chance to read it. When the interrupt routine returns the last time, 0x90 is popped into A and the comparison passes. In GBE+ this never happens.

On the intro scene where my emulator was hanging, it was the same code but the timing was slightly different: I was always one cycle short of getting the comparison to pass. I spent a few hours trying to find an off-by-one cycle timing error, but in the end I could only get the game to work by entering VBLANK one m-cycle later in double speed mode; IOW, triggering the VBLANK interrupt 8 cycles into scanline 0x90 instead of 4 cycles. This let the game work, and didn't cause any regressions in the other games I have, but I have no idea if it's the correct behaviour or not and don't have a flashcart to test it :/

I'm not sure how accurate the LCD timings are in GBE+, but hopefully this helps you get the game closer to booting. I figured since I'd already spent a bunch of time debugging this, I'd save you the time of duplicating the effort :p

**Comment by shonumi** [comment]
@CaptainCaffeine - Thanks for the info! I'll look into it soon. This behavior looks strikingly similar to Wizards and Warriors: Chapter X. Wonder if it's the same underlying problem.

**Comment by benderscruffy01** [comment]
Razor Freestyle Scooter (USA) graphic glitches
during gameplay bottom of screen glitchy
![razor](https://user-images.githubusercontent.com/48821663/55692343-ae62da00-59d9-11e9-816a-afbce4aaf3e6.PNG)
endrift fixed
https://github.com/mgba-emu/mgba/commit/c85d0b10967be088c101e85efda29b72730110d6

**Comment by benderscruffy01** [comment]
007 - The World Is Not Enough (USA, Europe) glitchy HUD
during gameplay there is a glitchy red line at the bottom of the HUD
![007](https://user-images.githubusercontent.com/48821663/55700964-06163b00-5a04-11e9-8c43-d81e878e4f45.PNG)
endrift fixed
https://github.com/mgba-emu/mgba/commit/a3c79c92d78c5802d0608639bc4feb87d2faa1d2

**Comment by benderscruffy01** [comment]
Warriors of Might and Magic (U) [C]
stuck on the title screen

**Comment by benderscruffy01** [comment]
4x4 World Trophy (Europe) (En,Fr,De,Es,It) (GB Compatible)
during gameplay runs really really slow

**Comment by benderscruffy01** [comment]
Worm's Armageddgon
Crash when selecting the quickstart game option:
endrift fixed
https://github.com/mgba-emu/mgba/commit/d054be88c7c48e42b0a3e33a9c47b281d97fc478
