### ISSUE TITLE
Material maps

### ISSUE THREAD

**Issue by lyonhrt** [shonumi/gbe-plus#48]
Would it be possible to have the ability to add a material map to a tile, and perhaps setting a tile as a light source, it could open up a lot of interesting looks to the game

Example:
![9gq1jd1jv1j71j71jz1ir9gq](https://cloud.githubusercontent.com/assets/20959583/24833788/c945f674-1ccb-11e7-8a4e-838901e0f7f9.png)
Normal
![9gq1jd1jv1j71j71jz1ir9gq_n](https://cloud.githubusercontent.com/assets/20959583/24833790/de456b7c-1ccb-11e7-89d5-2a6251b2634a.png)
so..
with normal applied it could look like this..
![example](https://cloud.githubusercontent.com/assets/20959583/24833803/3bd6768c-1ccc-11e7-8198-310517ea943a.png)

**Comment by shonumi** [comment]
About the material map, I think it's better for artists to apply it to whatever image they want to load up. This keeps the scope of CGFX focused on just loading the images rather than manipulating them. IMO, GBE+ shouldn't care about the source image, and it should leave them unaltered. 

For the lighting, it'd be possible in limited circumstances but kinda onerous to implement. I'm not too warm on the idea due to the associated code complexity involved, and it strays a bit from what I envisioned for CGFX (i.e. nothing than replacing 1 original tile with 1 custom tile, with some tricks to correctly pull that off). Now, I'm not going to say "No, end of story", just that I don't see it happening. I'll keep an open mind about it nonetheless. If I ever come up with some crazy method of passing CGFX info to the post-processing shaders, that might work.
