### ISSUE TITLE
Changing khz rate of audio changes the audio's pitch

### ISSUE THREAD

**Issue by RushJet1** [shonumi/gbe-plus#53]
Just as the title says, if you play the audio at a different rate than 48khz, it plays that much lower.  44khz is a few semitones lower than 48khz, 22khz is one octave lower than 44khz, etc.

**Comment by shonumi** [comment]
Yeah, long time issue from when this project used to be on Google Code. It should be straightforward to fix. The problem largely stems from the fact that the downsampling is pretty naive.

Although, in reality, 22KHz and 11KHz are novelties, I guess. Most systems should be able to hit 96KHz these days.

Expect a fix this weekend, maybe.

**Comment by shonumi** [comment]
@RushJet1 - Mind checking out the latest commit? c22d056f5daba0cc3008ed5366f2790b623e1eba should fix it now, but I want someone to double check.

Keep in mind that 11KHz and 22KHz are still not going to sound exactly like VBA-M or BGB because there is no filtering in GBE+. Frequencies that games generate that are too high (anything above 5.5KHz and 11KHz respectively) are going to cause aliasing. For most games it sounds about right.

**Comment by RushJet1** [comment]
The pitches are now correct, though the 11khz audio sounds hilarious due to lack of filtering ;)
