### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by Luraktinus** [shonumi/gbe-plus#56]
Could someone ad build instructions to the readme please?

i know that i need cmake, but i dont know how to configure the build.

**Comment by shonumi** [comment]
The build instructions are already part of the manual. You can find detailed information about the process there, and the file is available as a PDF and an ODT file. The README is intended as a quick little blurb rather than dedicated instructions. The README also points users to the manual for further questions, since that document covers pretty much everything about GBE+.
