### ISSUE TITLE
EXT_VRAM_ADDR problems corresponding with H and V flip flags

### ISSUE THREAD

**Issue by GregoryMcGregerson** [shonumi/gbe-plus#61]
I was testing Zelda Link's Awakening DX for GBC tonight and noticed that dumping the OBJs of Link when he's facing various directions the CGFX graphics don't show when H-flip is flagged using a manifest with EXT_VRAM_ADDR data for that replacement. It's an interesting bug and the solution is to not use VRAM addresses for OBJs but it's an gives the idea to have different replacements in the manifest depending of if the H or V flag is enabled or not, maybe? Or have those hash separately with a check box in the options or something.

Nice work getting GBC games to work with CGFX btw. I've been looking forward to that since forever. GBA CGFX next?! 🤞😄

**Comment by shonumi** [comment]
This game is actually rearranging VRAM tiles every time you switch directions, so it works in a way that's incompatible with the way EXT_VRAM_ADDR was designed.

Say you're facing right. Link's sprite is split into two. The front half (right-most half) is located in VRAM at 0x8020, and the rear half (left-most half) is located at 0x8000. Now if you turn left, Link's front half actually gets switched. It's at 0x8000 and the rear half is 0x8020. The graphics generate the same hash regardless of the H flag in GBE+, but depending on which direction you're facing when you dump it an apply EXT_VRAM_ADDR, it will associate it with VRAM addresses that are correct for one direction, but not the other.

This is just the way Nintendo designed their game engine. It shuffles tiles around. Other games keep the tiles the same, they just switch the H flags on the sprites. This behavior is beyond the scope of EXT_VRAM_ADDR as that's not the problem it was intended for. EXT_VRAM_ADDR is for replacing  graphics with the same hash, but for a specific VRAM address (generally this means for a specific situation, e.g. replace all white tiles during the title screen, but not on Level 1 or Level 2, or something).

If a tile can have more than one VRAM location, EXT_VRAM_ADDR should not be applied, as GBE+ may skip replacing the CGFX you want. Tiles that can exist at multiple VRAM locations can already be replaced without the EXT_VRAM_ADDR option (as you've noticed). OBJs are probably the worst candidates since they're the most likely to switch VRAM addresses. Stuff like title screens or other static menus are good candidates for EXT_VRAM_ADDR. Some regular BG tiles may be good candidates as well (e.g. Super Mario Land 1, almost all the tiles for every level never change addresses, almost), but a that's constantly changing BG VRAM addresses all the time (Wario Land or Kirby games) should avoid EXT_VRAM_ADDR.

I guess I really should make a tutorial about CGFX one of these days. I don't think I properly got the chance to explain EXT_VRAM_ADDR in the manual.

Glad you like the GBC support. Be warned it's still spotty (see some of the other recent CGFX issues). I'm working on fixes atm, and hopefully the Windows buildbot will be up and running soon so you can test it (assuming you run Windows?). GBA CGFX support will come... eventually, I hope. One of these years I guess.

**Comment by GregoryMcGregerson** [comment]
I see. It's been awhile since I used all this. I helped with the idea of Vram addresses way back when. I've been using Mesen lately and they way the graphic replacement on that is a bit different. I usually look at what is going on in vram in another emulator but I didn't really think to do that first. The meta sprite and BG replacement has expanded a lot since HDNes in Mesen. It's also quite complicated to get working as most of the advance manifest stuff has to be written in manually and it overwrites those changes if you use the built-in ripper.

Anyways yes I'm on Windows. I used to build it on my own machine but something happened last year and I could no longer get it to compile so I've been waiting for an official release. I'm glad to hear there will be a nightly binary.
