### ISSUE TITLE
[Request] Advanced CGFX (or ACGFX or short)

### ISSUE THREAD

**Issue by frozenLake** [shonumi/gbe-plus#63]
I would like to make a suggestion for an expansion of the CGFX system, known as ACGFX. The idea behind it is to have Custom Graphics that are affected by scripts and each other: for example, displaying another CGFX tile relative to others (in the case of pokemon, if you were to input the Advance Game's Sprites over the player, or to extend upon pokemon further, to have the graphics swapped out without worrying about overwriting a blank tile. Where as with the scripting idea, you could have it so that if you have the Fire Flower in Super Mario Land 2, you can swap Mario's palette to that of Fire Mario, regardless of it not happening in the original game, by displaying a different set of sprites if 0xA216 is equal to 0x03. Or change level palette based on another set of variables. Or even check a combination of level time with the current animation in order to make the animation somewhat smoother. The possibilities are basically endless.

But in short: Being able to replace "structures" of graphics (such as a battling Pokemon, or a Pyramid in the background), insert more tiles for certain graphics (like adding that extra sliver of tiles to the top of the player), and switch out graphics based on memory values. (for cases like Fire Mario and Megaman's Abilities)

**Comment by shonumi** [comment]
As cool as that idea sounds, and even though I've toyed with something like that myself, I'm going to have to say no.

The original idea behind CGFX was to take the "custom textures" feature from stuff like N64, GC, and Wii games, and transplant that onto the Game Boy. That also meant having the simplicity of dumping graphics, editing graphics, uploading them back into the game, and that's about it. Now, granted, the dumping process is *much* more elaborate than custom textures (thanks to the way 2D systems work), a lot of effort went towards making it so that all you had to do was choose what graphics you wanted to dump, edit them, and then have GBE+ handle the rest.

Beyond manifests and the EXT_VRAM_ADDR + EXT_AUTO_BRIGHT options, I'm not too keen on adding anything else. Basically being able to rewrite a game's underlying graphics engine not only sounds like a monumental coding task for GBE+, but it'd be a huge maintenance cost. Replacing certain tiles based on one value in memory is easy enough, but adding different combos, having different ones depend on others and such would prove cumbersome. Chiefly, however, it looks like "feature creep", and that's something I want to avoid at all costs. 

It's possible to get GBE+ to add all of these things, no doubt, but it run afoul of the original scope I had in mind.

**Comment by frozenLake** [comment]
Fair enough. I know that Mesen added the functionality to replace tiles based on surrounding tiles, but that does sound like a huge pain to implement.

(When can we expect CGFX for GBA games, by the way?)

**Comment by meepingsnesroms** [comment]
GBA games are already 16bit they don't need cgfx, just replace the tiles with a ROM hack.

**Comment by shonumi** [comment]
I have not ETA on GBA CGFX. I need to rewrite a lot of the GBA core's LCD code for it to actually be viable. The rewrite is something I've been planning for a while but postponed a lot. Since the 2D engine of the NDS is copy+paste of the GBA, and GBE's NDS core has much better LCD code, I might wait until the NDS core matures then backport all of the work to GBE's GBA core. At that point, GBA CGFX should be doable.

@meepingsnesroms - With CGFX, you can do HD replacements though. Additionally, no matter how much you hack a ROM, you're often limited to 16 colors per tile (that limit can be exceeded on real hardware, but it costs precious VRAM), so CGFX can do 64 colors per-tile even with just 1:1 replacements.
