### ISSUE TITLE
Export custom graphics changes to new rom

### ISSUE THREAD

**Issue by gingemonster** [shonumi/gbe-plus#88]
Maybe I am missing something but is there a function that allows me to export a rom once I have added custom graphics?

**Comment by shonumi** [comment]
Custom Graphics aren't injected or added to a ROM. The ROM itself is left unchanged. All GBE+ does is look at the dynamic data stored in VRAM at any given moment, then instead of drawing normal 8-bit Game Boy graphics, it draws user-generated graphics. It's basically the equivalent of "HD textures" popular for N64 emulators or in Dolphin. Nothing about the game itself is changed, so there's no way to send those changes back to the ROM.

**Comment by gingemonster** [comment]
that's a shame, thanks for explaining
