### ISSUE TITLE
Turbo Turtle Adventure (USA) black screen

### ISSUE THREAD

**Issue by benderscruffy01** [shonumi/gbe-plus#99]
using 1.3
nothing but a black screen

**Comment by shonumi** [comment]
Could I ask you to centralize all future GBA issues into a current one? It's actually harder to keep track of everything when they're spread across 6+ issues. #32 would be preferable. Use #29 and #30 for DMG and GBC bugs as well.

Normally it's fine to have separate issues, but since you have found a lot, I'd like to keep them all in the same spot.

**Comment by shonumi** [comment]
Fixed as of 1a078357a8b79281aabe717ea57aa243c99b0656

**Comment by benderscruffy** [comment]
still a black screen
am using 
https://github.com/shonumi/gbe-plus/commit/3638dc19d47dc2ce8c1198aab36e3e9150b71536

**Comment by shonumi** [comment]
It was fixed in 1a07835, promptly broken in 09973964ded0e7b9c42ddcbae288300c790c6d53, then fixed in 5fbddf80c6fb4aaf85a8f7d5f3c08056e2d357fd
